config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'lessons/index'
  get 'lessons/view'
  get 'lessons/start/:id' => 'lessons#view', as: 'start_test'
  post 'lessons/start/:id' => 'lessons#answer', as: 'answer_for_test'
  get 'lessons/results/:id' => 'lessons#results', as: 'results_test'

  resources :answers
  resources :questions
  resources :tests do
    post 'check_all_user_at_group', on: :member
    post 'check_user_for', on: :member

  end
  resources :users
  resources :groups
  get 'admin/index'
  root 'home#index'
  get 'lessons/index', as: 'user_root'

end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  belongs_to :test
  has_many :answers


end

app/controllers/questions_controller.rb
class QuestionsController < AdminController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new(test_id:params[:test_id])
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to test_path(@question.test_id), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to test_path(@question.test_id), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to test_path(@question.test_id), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:test_id, :flag, :text)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Вопрос <br>
    <%= f.text_field :text%>
  </div><%= f.hidden_field :test_id%>
    <br>

  <div class="actions">
    <%= f.submit  'Далее', class:'btn btn-warning'%>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Test</th>
      <th>Flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.test_id %></td>
        <td><%= question.flag %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h3>Новый вопрос</h3>

<%= render 'form' %>

<%= link_to 'Back', test_path(params[:test_id]) %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test:</strong>
  <%= @question.test_id %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @question.flag %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>