config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'lessons/index'
  get 'lessons/view'
  get 'lessons/start/:id' => 'lessons#view', as: 'start_test'
  post 'lessons/start/:id' => 'lessons#answer', as: 'answer_for_test'
  get 'lessons/results/:id' => 'lessons#results', as: 'results_test'

  resources :answers
  resources :questions
  resources :tests do
    post 'check_all_user_at_group', on: :member
    post 'check_user_for', on: :member

  end
  resources :users
  resources :groups
  get 'admin/index'
  root 'home#index'
  get 'lessons/index', as: 'user_root'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < AdminController

  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new(question_id:params[:question_id])
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to test_path(@answer.question.test_id).to_s + "#" + @answer.question.id.to_s, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to test_path(@answer.question.test_id), notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:text, :question_id, :flag)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Вариант ответа <br>
    <%= f.text_field :text %>
    <%= f.hidden_field :question_id, value: params[:question_id] %>
  </div>

  <div class="field">

    <%= f.label :flag, "Верно?", :for => "answer_flag" %>
    <%= f.check_box(:flag, {}, "1", "0")%>

  </div>
  <div class="actions">
    <%= f.submit 'Сохранить', class:'btn btn-warning' %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Question</th>
      <th>Flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.text %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.flag %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>Новый ответ</h1>

<%= render 'form' %>

<%= link_to 'назад', test_path(@answer.question.test_id), anchor: @answer.question.id %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @answer.text %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @answer.flag %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>