config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'lessons/index'
  get 'lessons/view'
  get 'lessons/start/:id' => 'lessons#view', as: 'start_test'
  post 'lessons/start/:id' => 'lessons#answer', as: 'answer_for_test'
  get 'lessons/results/:id' => 'lessons#results', as: 'results_test'

  resources :answers
  resources :questions
  resources :tests do
    post 'check_all_user_at_group', on: :member
    post 'check_user_for', on: :member

  end
  resources :users
  resources :groups
  get 'admin/index'
  root 'home#index'
  get 'lessons/index', as: 'user_root'

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  def index
    @tests = current_user.tests_for_users.all
  end

  def answer
    test = current_user.tests_for_users.find_by(test_id: params[:id]).test
    count = current_user.test_user_logs.where(question_id: test.questions).count

    right = test.questions[count].answers.find_by(flag: 1)

    current_user.test_user_logs.create(question_id: test.questions[count].id, point: answer_params[:id].to_i)

    if right.id == answer_params[:id].to_i
      render js: "$('.right').text('Вы правы!').css('color','green'); $('.form').text(''); $('.next').show(); "

    else
      render js: "$('.right').text('Вы не правы! Правильный ответ - #{right.text}').css('color','red'); $('.form').text(''); $('.next').show()"
    end
  end

  def view
   #чтобы в урл не светить ид вопроса сделал остслеживание текущего вопроса в логе прохождения теста, урл в тесте всегда будет одинаковым
    @test = current_user.tests_for_users.find_by(test_id: params[:id]).test

    count = current_user.test_user_logs.where(question_id: @test.questions).count

    if count == 0
      @question = @test.questions.first
    else
      @question = @test.questions[count]
    end
    redirect_to results_test_path(params[:id]) if count == current_user.tests_for_users.find_by(test_id: params[:id]).test.questions.all.count
  end

  def results
    @test = current_user.tests_for_users.find_by(test_id: params[:id]).test

    log = current_user.test_user_logs.where(question_id: @test.questions)
    r = 0
    log.each do |item|
      if item.point != item.question.answers.find_by(flag: 1).id
      r += 1
      end
    end
    if r > @test.credit.to_i
      @res = 'Тест не пройден'
    else
      @res = 'Поздравляем Вы прошли тест'
    end

  end

  private
  def answer_params
    params.require(:answer).permit(:id)
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/index.html.erb
<div class="row">
  <div class="col-sm-3">
    <h4>Мои тесты</h4>
    <ul>
      <% @tests.each do |item|%>
        <li><%= item.test.text %> <%= link_to 'Пройти', start_test_path(item.test_id) %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-9">

  </div>
</div>

app/views/lessons/results.html.erb
<h3>Тест: <%= @test.text %> </h3>
<br>
<h4> <%= @res %> </h4>
<%= link_to 'Назад', lessons_index_path%>

app/views/lessons/view.html.erb
<h3>Тест: <%= @test.text %> </h3>
<br>
<h4><i>Вопрос:</i> <%= @question.text %></h4>

<br>
<strong>Варианты ответов</strong>

<br><div class="right"></div><br>
<div class="form">
  <%= form_tag( answer_for_test_path(@test.id), method: :post, remote: true) do %>
      <%= collection_radio_buttons(:answer, :id, @question.answers.all, :id, :text, html_options: { class: 'form-control' }) do |b| %>
          <%= b.label { b.radio_button + " " + b.text } %><br>
      <% end %>
      <br>
  <%= button_tag 'Ответить', type: 'submit', class: 'btn btn-success' %>
  <% end %>
</div>
<br>
<div class="next">
  <%= link_to 'Далее', start_test_path(@test.id), class: 'btn btn-success'%>
</div>
<style>
  .next{
    display:none;
  }
</style>